### PR TITLE
Replaces ugettext_lazy by gettext_lazy

### PR DESCRIPTION
**Pull request by frague59**
Updates models.py to use gettext_lazy instead of ugettext_lazy

### CODE REVIEW

**Comment by etianen** [comment]
Thank you!

I'm looking at pushing out a release today or tomorrow.

**Comment by frague59** [comment]
You're welcome !

**Comment by frague59** [comment]
Could you upload the updated package to pypi ? 

Thanks !

**Comment by etianen** [comment]
Done already :)

**Pull request merged**
