### PR TITLE
adding the ability to include or exclude models while using the revis…

### PR DESCRIPTION
**Pull request by yazanpsut**
…ion middleware.

### CODE REVIEW

**Comment by yazanpsut** [comment]
@yorkedork @bartek @charettes @blueyed any comments about this pull request?

**Comment by etianen** [comment]
Thanks for contributing!

I'm confused by this. The proposed setting seems to exclude certain models from version control altogether, not just with RevisionMiddleware.

**Comment by yazanpsut** [comment]
@etianen well... It seemed legit when you are using the middleware because it controls all models, but your point is correct where when ever you use it, you can include or exclude models at all time.

**Comment by etianen** [comment]
You can simply exclude models by not registering them with reversion, surely?

**Comment by yazanpsut** [comment]
@etianen but if you are using the middle ware, can you do that?

**Comment by etianen** [comment]
The middleware will only version models that have been registered with
reversion, either via reversion.register() or via the admin integration.

**Pull request closed without merging**
