### PR TITLE
Slovenian translation

### PR DESCRIPTION
**Pull request by borplestenjak**
Hi! I added the Slovenian translation.

### CODE REVIEW

**Comment by etianen** [comment]
Awesome! Thanks for contributing!

I'll push out a release tomorrow, all things being good.

**Comment by borplestenjak** [comment]
Hi, I noticed that version 3.0.6 is released that should include the Slovenian translation, but something must went wrong as sl_SI folder is not included in reversion/locale in the latest release https://github.com/etianen/django-reversion/commit/3356aa18084ed2b6ab1aa39c33b9bb9a87df33d8

or in the download available on pypi.

**Comment by etianen** [comment]
Oh, crap. Looks like I've got my branches in a twist. I'll sort this out now with a new 3.0.7 release.

**Comment by etianen** [comment]
Fixed in v3.0.7. Sorry!

**Pull request merged**
