### PR TITLE
Fixed tests with Django 2.0

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Not ready, still two errors to fix.

**Comment by claudep** [comment]
Now ready.

**Comment by claudep** [comment]
One change affects the main code, so a new release will be needed to support Django 2.0.

**Comment by etianen** [comment]
Damn fine work!

**Comment by etianen** [comment]
While Django 2.0 is in development, I think it's fine to require installing django-reversion from the GitHub repo.

**Comment by claudep** [comment]
Sure no rush. However, Django 2.0 is feature frozen now, so if we can have a release during the next two months, it encourages people to test the new Django before its .0 release.

**Pull request merged**
