### PR TITLE
Reintroduce pre_revision_commit and post_revision_commit signals

### PR DESCRIPTION
**Pull request by carlosxl**
Rationale: https://github.com/etianen/django-reversion/issues/571
Related commit: 09ce3764c1404747ebb90379cd79e193f3f58164

### CODE REVIEW

**Comment by carlosxl** [comment]
@etianen not sure
1. if the signal signature aligns with your design; and
2. if this is the right strategy to test the signals.

Please take a look, thanks!

**Comment by etianen** [comment]
This looks perfect!

1. Sure does!
2. I've not used mock much, but I like how those tests look. :)
3. I believe that the signals are dispatched inside the transaction block, which is good, as it contains their database side-effects inside the same transaction.

If you could also add a `signals.rst` to the docs, and link it in, that would finish this perfectly.

(Unfortunately, having spent a long time updating the docs recently, I've since come to realize that there are much better ways of formatting them using python hooks built into sphinx. Please follow the existing style for now, even if it's a bit odd!)

**Comment by carlosxl** [comment]
Took a shortcut to copy most of it from the original doc. See if it is consistent with the existing style :)

**Comment by etianen** [comment]
Lovely job, thanks!

**Comment by carlosxl** [comment]
Great project here! Thanks!

**Pull request merged**
