### PR TITLE
Fix issue with admin and special characters in primary keys

### LINKED ISSUE #661: Admin broken when using primary keys with underscores
If you have a model with a text based primary key with any of the special characters which django admin quotes, the history list is unable to be browsed. Once that is fixed, the changes are unable to be reverted due to a similar issue.

It's a pretty simple fix, pull request incoming.

### PR DESCRIPTION
**Pull request by achidlow**
Issue is as described in #661. Fix is pretty straightforward, just needed to quote/unquote in the right places.

Also adds unit tests that demonstrate issue and verify the fix.

### CODE REVIEW

**Comment by achidlow** [comment]
I've reduced it down to a single unit test. I think it would be good to have to check for regressions, as it's an easy thing to forget when making changes. If you'd prefer not to have any unit tests at all let me know and I'll remove all together.

Not sure why travis is failing. It doesn't look like it's caused by the addition of the unit test? At least, not in an obvious way. Any ideas?

**Comment by etianen** [comment]
Cool, thanks. I think this is a good compromise on tests. :)

I'll see if I can work out why the tests are breaking on Python 2.7...

**Comment by etianen** [comment]
For some reason, the tests stopped breaking. Odd. :S

Thanks for your time on this!

**Comment by achidlow** [comment]
No worries, thanks for the super quick merge!

**Pull request merged**
