### PR TITLE
Simplified middleware (stop supporting Django < 1.11)

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
The single Travis error is apparently a timeout issue when getting Python 3.5 package.

**Comment by etianen** [comment]
Yeah, I see. I've restarted the build.

**Comment by claudep** [comment]
Oh, I had just forgotten a docs removal.

**Comment by claudep** [comment]
@etianen, thanks for merging. Just for information, you can setup Github to merge PRs without creating a merge commit to have a somewhat cleaner history, in case you missed it.

**Pull request merged**
