### PR TITLE
Add `is_authenticated` compatibility django 1.10+

### PR DESCRIPTION
**Pull request by KhasanovBI**

### CODE REVIEW

**Comment by KhasanovBI** [comment]
refs #573

**Comment by etianen** [comment]
Thanks!

I think we'd be better off using capability testing, rather than version checking here. Something like isinstance(user.is_authenticated, bool)

**Comment by KhasanovBI** [comment]
But in django 1.10 `is_authenticated` can be a property or attribute.

**Comment by etianen** [comment]
I meant like:

``` py
if isinstance(user.is_authenticated, bool):
    return user.is_authenticated
return user.is_authenticated()
```

That should work for the case of CallableBool and bool.

**Comment by KhasanovBI** [comment]
But that's not work in case of CallableBool
image
So in django with version less than 1.10 I can't import CallableBool to check isinstance of it.

**Comment by etianen** [comment]
Damn, you're right. 

I hate using version number checks, but in this case I can't see a better alternative.

**Pull request merged**
