### PR TITLE
Add tests for Django master, allowing failures

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
#668 should be solved first

**Comment by etianen** [comment]
Thanks!

**Comment by claudep** [comment]
Thanks, but sorry, I was not yet certain it worked, it would have been better to wait for a successful test run first :-)
I think we also need to allow the master failures at tox level (probably with `ignore_outcome`)

**Comment by claudep** [comment]
You might try to add:
```
ignore_outcome =
    djangomaster: True
```
under `[testenv]`

**Comment by etianen** [comment]
Thanks, that fixed it.

What with pyenv, too and travis, there's a lovely mess of configuration at
play here, in an environment you can only access with a git push. *Sigh...*

**Comment by claudep** [comment]
Sure, but you can also test with pull requests before committing to the main master branch (and force push to pull requests until the tests pass).

**Pull request merged**
