### PR TITLE
Fix for checking db savepoints

### PR DESCRIPTION
**Pull request by aloskutov-ki11**
Fix for checking db savepoints

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for the pull request.

What problem is it fixing?

**Comment by aloskutov-ki11** [comment]
All my projects are encapsulated in docker containers and Dockerfile for container with django has string `RUN python ./manage.py collectstatic --noinput`. If you run `docker build server` container has no access to database and build breaks.

**Comment by etianen** [comment]
I don't think that accessing connection.features opens a database connection. Is it that the docker container doesn't contain the database settings, which is causing an ImproperlyConfigured exception to be raised?

If so, surely the fix is to provide the database settings to the container?

Alternatively, we could move the check to the recover/revert view to delay the check until runtime.

**Comment by aloskutov-ki11** [comment]
Yes you are right. All database settings I put in a file with environment variables and container building process knows nothing about them. This .env file is connected to the container only when it's lainched

**Pull request closed without merging**
