### PR TITLE
Remove django.contrib.admin dependency from django-reversion

### PR DESCRIPTION
**Pull request by codearm-docker**
In many cases `django-admin` is not used and it is an overhead for the project. Using `django-reversion` forces the developer to include `django.contrib.admin` in the `INSTALLED_APPS` even if it is not used. This is because it imports the `LogEntry` model from `django-admin` in one of the files.

This PR closes issue #744 by making the dependency of the `LogEntry` model from `django.contrib.admin` application optional. Moreover, unused imports have been removed and sorted.

### CODE REVIEW

**Comment by etianen** [comment]
Sweeeeeet!

Thanks. :)

**Comment by user37596** [comment]
Thank you very much for this.

@etianen May I inquire when a new version is planned to be released with this fix? We want to wait for it before using this package, so we don't have to later revert the admin migrations and remove it from the installed apps.

**Comment by etianen** [comment]
Sometime next week, no worries! :)

**Comment by etianen** [comment]
It is done. :)

v3.0.4

**Comment by user37596** [comment]
Thank you! Only one thing, the `createinitialrevisions` does not seem to work without admin being in the installed apps. `BaseRevisionCommand` uses `admin.autodiscover()`, which fails: 

```
» docker-compose exec web python manage.py createinitialrevisions
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 155, in get_app_config
    return self.app_configs[app_label]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/module_loading.py", line 44, in autodiscover_modules
    if register_to:
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 529, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'admin'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 155, in get_app_config
    return self.app_configs[app_label]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/reversion/management/commands/createinitialrevisions.py", line 58, in handle
    for model in self.get_models(options):
  File "/usr/local/lib/python3.7/site-packages/reversion/management/commands/__init__.py", line 31, in get_models
    admin.autodiscover()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python3.7/site-packages/django/utils/module_loading.py", line 53, in autodiscover_modules
    if register_to:
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 529, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'admin'.
```

**Comment by etianen** [comment]
Oh, how annoying. I guess that was missed by the original PR.

I'll happily take a PR to fix this.

**Pull request merged**
