### PR TITLE
Support asyncio views

### PR DESCRIPTION
**Pull request by bellini666**
Use contextvars instead of threading.local to support async views.

I tried to do the smallest changes that I could, but using contextvars that code can be simplified a lot.

### CODE REVIEW

**Comment by etianen** [comment]
Hi,

Thanks for this! It's a good change. Unfortunately, it requires Python 3.7+, which is going to be supported by Django LTS until early 2024!

I'd like to keep this MR open until then, but I don't think I can drop support for Python 3.6 while Django LTS supports its.

Alternatively, I'd consider a compatibility shim that used contextvars and fell back to thread-local state. That seems like it would be a relatively unobtrusive change.

**Comment by etianen** [comment]
You make an excellent point. Go ahead and drop 3.6 from the matrix and
we'll get this merged. :)

**Comment by bellini666** [comment]
@etianen nice :)
Just made the change, think it should be enough

**Comment by etianen** [comment]
Thanks! I'll get this into a release ASAP.

**Pull request merged**
