### PR TITLE
Optimize deleted objects query

### PR DESCRIPTION
**Pull request by GeyseR**
Optimization is based on
1) switching casting to an appropriate type for Version.object_id instead of the primary key
2) for Postgres on using DISTINCT ON with conditional expressions

### CODE REVIEW

**Comment by etianen** [comment]
Thank you! This is a difficult query to optimize, so I'm pretty excite when something like this comes along.

I can't really accept an optimization patch without before and after benchmarks, however. Could you provide before and after benchmarks for the following scenarios:

(Large | small) version table, (large | small) model table, (no | many) deleted objects.

Or other scenarios, if you think it's appropriate.

**Comment by GeyseR** [comment]
I've tested this scenario on a live project on the table with 115K existing rows and 10K deleted rows, and the solution works much faster, like 0.5 seconds vs 15s.

I'll try to provide some synthetic tests soon. 
If you have any ideas or previous examples of the benchmarks, that would be helpful :)

**Comment by etianen** [comment]
Interesting, and encouraging!

Benchmarking on your dataset with the before and after code would be
sufficient, tbh.

**Comment by GeyseR** [comment]
here it is
```
Existing| Deleted	| Old time 		 | New time
171536  | 1 		| 0:00:19.774807 | 0:00:00.136772
1899    | 140 		| 0:00:00.569091 | 0:00:00.007093
402654  | 2989	 	| 0:00:33.789328 | 0:00:00.345087
1476468 | 6463 		| 0:00:36.706675 | 0:00:00.470335
158723  | 0 		| 0:00:26.714242 | 0:00:00.364553
524738  | 4658 		| 0:00:27.682335 | 0:00:03.061931
50727   | 846 		| 0:00:01.349259 | 0:00:00.076102
182551  | 6806 		| 0:00:05.901048 | 0:00:00.448359
11653   | 848 		| 0:00:33.278280 | 0:00:00.516516
93540 	| 427 		| 0:00:11.173351 | 0:00:00.328175
2331 	| 3 		| 0:00:00.017268 | 0:00:00.004476
112231 	| 434 		| 0:00:04.787984 | 0:00:00.682868
325305 	| 37415 	| 0:00:08.344689 | 0:00:00.809080
13829 	| 130 		| 0:00:17.498631 | 0:00:04.824630
15671 	| 459 		| 0:00:03.479546 | 0:00:01.302051
4402 	| 57823 	| 0:00:02.915513 | 0:00:00.667132
2153 	| 0 		| 0:00:00.023557 | 0:00:00.003816
7622 	| 79 		| 0:00:00.061769 | 0:00:00.009884
7354 	| 10 		| 0:00:00.058137 | 0:00:00.008684
3686 	| 50161 	| 0:00:00.599514 | 0:00:00.440178
49187 	| 0 		| 0:00:00.305760 | 0:00:00.030057
61178 	| 233380 	| 0:00:02.370193 | 0:00:01.973392
94983 	| 9951 		| 0:00:01.414094 | 0:00:00.253754
68179 	| 16763 	| 0:00:01.445508 | 0:00:00.167908
545040 	| 19131 	| 0:00:05.287630 | 0:00:00.661380
121303 	| 4047 		| 0:00:01.271823 | 0:00:00.186989
162439 	| 8144 		| 0:00:01.804782 | 0:00:00.301282
4 	| 0 		| 0:00:00.006102 | 0:00:00.002966
21 	| 0 		| 0:00:00.010503 | 0:00:00.004099
9 	| 0 		| 0:00:00.005437 | 0:00:00.002856
118225 	| 10762 	| 0:00:01.529504 | 0:00:00.375201
3344987 | 160791 	| 0:01:16.863503 | 0:00:21.369741
4010 	| 3 		| 0:00:00.037191 | 0:00:00.004252
```

the benchmark code:
```python
from django.core.management import BaseCommand
from django.db.models import Exists, OuterRef
from django.db.models.functions import Cast
from django.utils import timezone

from reversion import get_registered_models
from reversion.models import Version

class Command(BaseCommand):
    def handle(self, *args, **options):
        all_registered_models = get_registered_models()
        self.stdout.write('Existing | Deleted | Old time | New time')
        for model in all_registered_models:
            start = timezone.now()
            old_deleted_count = Version.objects.get_deleted(model).count()
            old_time_end = timezone.now()
            new_deleted_count = self.get_deleted_new(model).count()
            new_time_end = timezone.now()
            existing_count = model.objects.count()
            assert old_deleted_count == new_deleted_count, str(model)
            self.stdout.write(
                f'{existing_count} | {old_deleted_count} | '
                f'{old_time_end - start} | {new_time_end - old_time_end} | ',
            )

    def get_deleted_new(self, model, model_db=None):
        model_qs = (
            model._default_manager.using(model_db).filter(
                id=Cast(OuterRef("object_id"), model._meta.get_field('id')),
            ).values('id')
        )
        subquery = Version.objects.get_for_model(
            model,
            model_db='default',
        ).filter(
            ~Exists(model_qs),
        ).order_by('object_id', '-pk').distinct('object_id').values('pk')
        return Version.objects.filter(pk__in=subquery)
```

**Comment by etianen** [comment]
Okay, it's hard to argue with that!

This is great work. I'll push out a release with it next week. :heart:

**Comment by etianen** [comment]
Released in 3.0.9

**Pull request merged**
